# Generated by Django 3.2.18 on 2023-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newpost_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='Username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Ethnicity',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.FloatField(max_length=200),
        ),
    ]
