# Generated by Django 4.1.7 on 2023-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='AgeGroup',
            field=models.IntegerField(max_length=200),
        ),
    ]
