# Generated by Django 4.1.7 on 2023-05-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mymodel_agegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='AgeGroup',
            field=models.IntegerField(),
        ),
    ]
