# Generated by Django 4.1.7 on 2023-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Image1',
        ),
        migrations.AddField(
            model_name='profile',
            name='Hydration',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
    ]
